FIND_PATH(PIXMAN_INCLUDE_DIR /pixman.h
/usr/include/pixman-1
)

FIND_LIBRARY(PIXMAN_LIBRARY
NAMES pixman-1
PATHS
)

SET(PIXMAN_FOUND "NO")

IF(PIXMAN_LIBRARY)
    SET(PIXMAN_FOUND "YES")
    MESSAGE(STATUS "Found Pixman libs: ${PIXMAN_LIBRARY}")
    MESSAGE(STATUS "Found Pixman includes: ${PIXMAN_INCLUDE_DIR}")
ENDIF(PIXMAN_LIBRARY)

MARK_AS_ADVANCED(
    PIXMAN_INCLUDE_DIR
    PIXMAN_LIBRARY
)
