FIND_PATH(PNG_INCLUDE_DIR png.h /usr/include)

FIND_LIBRARY(PNG_LIBRARY
NAMES png
PATHS
)

SET(PNG_FOUND "NO")

IF(PNG_LIBRARY)
    SET(PNG_FOUND "YES")
    MESSAGE(STATUS "Found PNG libs: ${PNG_LIBRARY}")
    MESSAGE(STATUS "Found PNG includes: ${PNG_INCLUDE_DIR}")
ENDIF(PNG_LIBRARY)

MARK_AS_ADVANCED(
    PNG_INCLUDE_DIR
    PNG_LIBRARY
)
